services:
  - type: web
    name: fashion-store-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: 4215822a60d9d592a8d392d6b9ae0bcdeb3996c46fee41d7fabf747944782f36
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: saikiran13720@gmail.com
      - key: EMAIL_PASS
        value: yhkchphtviuyaaqs
      - key: MONGO_URI
        value: mongodb+srv://saikiran85229:5ICoQCyOSuJy5VEL@cluster0.anvqnoh.mongodb.net/fashion_db?appName=Cluster0
      - key: CLOUDINARY_CLOUD_NAME
        value: dzqlqutma
      - key: CLOUDINARY_API_KEY
        value: "473544246922355"
      - key: CLOUDINARY_API_SECRET
        value: 4E0K7F5jnzqqV7rXBcs3NIDkeeA
